# Generated by Django 4.1.5 on 2023-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0022_alter_customuser_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wallet",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x000002A947CBAC00>", max_length=200
            ),
        ),
    ]
