# Generated by Django 4.1.5 on 2023-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sizevariant',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
