# Generated by Django 4.1.5 on 2023-03-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizevariant_stock'),
        ('orders', '0002_orderproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='sizevariant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant'),
        ),
    ]
