# Generated by Django 4.1.5 on 2023-03-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='Stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
